### ISSUE TITLE
Settings Panel

### ISSUE THREAD

**Issue by fmjosuel** [esengoba/SWE_Project#31]
## Notes
This includes enabling sound and timer.

**Comment by esengoba** [comment]
Settings prepare a template for the settings panel
Review the requirements doc/test cases

**Comment by Ropa94** [comment]
Settings template has been created. Back button not working well. Still to implement sound and timer properly. Will be based on current(future) working implementations of those in the game.

**Comment by esengoba** [comment]
good job!
