### ISSUE TITLE
Timer starts counting before hitting ready button

### ISSUE THREAD

**Issue by fmjosuel** [esengoba/SWE_Project#52]
Timer should start counting when the player hits "Ready" button. Currently, it counts as soon as the program is launched.

**Comment by esengoba** [comment]
I don't see this as a problem. The timer starts to count down from 10 at the start of each question.

**Comment by esengoba** [comment]
If you're trying to connect the score with the timer, then you want to use the variable i not the timer variable itself.

**Comment by fmjosuel** [comment]
@esengoba that's not quite what this bug means. Right now, by the time you reach the first question, you'll find the timer already counting. This is an issue just for the first question, the rests are fine. Maybe you have a different version than mine, in which case it should be nice to update changes on master.

**Comment by fmjosuel** [comment]
I just quickly addressed it. I'll close the issue as soon as the PR above is reviewed.

**Comment by esengoba** [comment]
Yeah my version of code didn't have that line.

**Comment by esengoba** [comment]
Addressed.
